// ══════════════════════════════════════════
//  BASE DE DONNÉES PLANTES — 40+ espèces
//  Chaque plante : phases annuelles (mois 1-12), besoins eau, wiki, conseils saisonniers
// ══════════════════════════════════════════

// Phases possibles: 'dormant','plantation','croissance','floraison','recolte','taille'
const PHASE_INFO = {
  dormant:   { label: 'Dormance',   icon: '💤', color: '#6a9b6e' },
  plantation:{ label: 'Plantation', icon: '🌱', color: '#81c784' },
  croissance:{ label: 'Croissance', icon: '🌿', color: '#4caf50' },
  floraison: { label: 'Floraison',  icon: '🌸', color: '#f06292' },
  recolte:   { label: 'Récolte',    icon: '🧺', color: '#ffb74d' },
  taille:    { label: 'Taille',     icon: '✂️', color: '#4fc3f7' },
};

const PLANT_LIBRARY = [
  // ───────── LÉGUMES-FRUITS ─────────
  { key:'tomate', name:'Tomates', emoji:'🍅', category:'Légumes', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Tomate',
    desc:"Plante annuelle gourmande en eau et en soleil, à tuteurer dès la croissance.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'plantation',5:'croissance',6:'croissance',7:'floraison',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante en place après les Saints de Glace (mi-mai). Tuteure dès 20cm.",summer:"Arrose tous les jours, supprime les gourmands chaque semaine.",autumn:"Termine la récolte avant les premières gelées, fais mûrir les vertes à l'intérieur.",winter:"Repos total, nettoie et désinfecte les pots pour l'an prochain."}},
  { key:'framboisier', name:'Framboisier', emoji:'🍓', category:'Fruits', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Framboisier',
    desc:"Arbuste fruitier vivace à racines profondes, nécessite un grand pot.",
    months:{1:'dormant',2:'dormant',3:'taille',4:'croissance',5:'croissance',6:'floraison',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille les cannes mortes en mars, paille le pied.",summer:"Récolte au fur et à mesure, arrose abondamment par forte chaleur.",autumn:"Coupe les cannes ayant fructifié au ras du sol.",winter:"Protège le pot du gel avec un voile d'hivernage."}},
  { key:'fraisier', name:'Fraisier', emoji:'🍓', category:'Fruits', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Fraisier',
    desc:"Petit fruit facile en pot, apprécie le soleil et un sol drainant.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'taille',9:'croissance',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Retire les vieilles feuilles abîmées par l'hiver.",summer:"Récolte tôt le matin, retire les stolons si pas besoin de bouturer.",autumn:"Plante de nouveaux pieds ou stolons.",winter:"Paille pour protéger du gel."}},
  { key:'poivron', name:'Poivron', emoji:'🫑', category:'Légumes', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Poivron',
    desc:"Demande chaleur et soleil constant, sensible au froid.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'plantation',5:'croissance',6:'croissance',7:'floraison',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Ne sors qu'après tout risque de gel, min 15°C la nuit.",summer:"Arrosage régulier, évite le stress hydrique qui fait tomber les fleurs.",autumn:"Récolte avant les nuits fraîches en dessous de 10°C.",winter:"Annuelle en climat tempéré, recommence chaque année."}},
  { key:'aubergine', name:'Aubergine', emoji:'🍆', category:'Légumes', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Aubergine',
    desc:"Très gourmande en chaleur et en eau, grand pot nécessaire.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'plantation',6:'croissance',7:'floraison',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante quand le sol atteint 15°C minimum.",summer:"Arrose au pied, paille pour garder l'humidité.",autumn:"Récolte avant que la peau ne devienne terne.",winter:"Aucune activité, plante annuelle en climat tempéré."}},
  { key:'courgette', name:'Courgette', emoji:'🥒', category:'Légumes', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Courgette',
    desc:"Très productive, demande un grand bac et beaucoup d'eau.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'floraison',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème ou plante après les dernières gelées.",summer:"Récolte tous les 2 jours pour stimuler la production.",autumn:"Dernières récoltes avant le ralentissement.",winter:"Plante annuelle, rien à faire."}},
  { key:'concombre', name:'Concombre', emoji:'🥒', category:'Légumes', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Concombre',
    desc:"Grimpant ou rampant, à tuteurer en pot pour gagner de la place.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'floraison',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Installe un treillis dès la plantation.",summer:"Arrose abondamment, le concombre est composé à 95% d'eau.",autumn:"Récolte avant les premières fraîcheurs.",winter:"Rien, plante annuelle."}},
  { key:'piment', name:'Piment', emoji:'🌶️', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Piment',
    desc:"Plus résistant à la sécheresse que le poivron, adore le plein soleil.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'plantation',5:'croissance',6:'floraison',7:'recolte',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante au chaud, sensible aux gelées tardives.",summer:"Laisse sécher légèrement entre arrosages pour plus de piquant.",autumn:"Récolte avant le premier froid, fais sécher les fruits restants.",winter:"Peut survivre en intérieur lumineux."}},

  // ───────── AROMATIQUES ─────────
  { key:'menthe', name:'Menthe', emoji:'🌿', category:'Aromates', freq:1, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Menthe',
    desc:"Vivace très envahissante, à isoler en pot dédié. Aime l'humidité.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre vite, divise la touffe si trop dense.",summer:"Garde le substrat humide en permanence, récolte au besoin.",autumn:"Coupe court avant l'hiver pour la forme.",winter:"Les parties aériennes meurent, repart au printemps."}},
  { key:'basilic', name:'Basilic', emoji:'🌱', category:'Aromates', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Basilic',
    desc:"Annuelle fragile au froid, déteste l'eau sur les feuilles.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante après les dernières gelées, min 12°C la nuit.",summer:"Pince les fleurs pour prolonger la récolte de feuilles.",autumn:"Rentre en intérieur lumineux si tu veux prolonger.",winter:"Meurt au gel, à ressemer chaque année."}},
  { key:'persil', name:'Persil', emoji:'🌱', category:'Aromates', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Persil',
    desc:"Bisannuelle, monte en graine la 2e année. Préfère la mi-ombre en été.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'recolte',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème ou plante, germination lente (3 semaines).",summer:"Place à mi-ombre si plein soleil trop fort, garde humide.",autumn:"Continue à récolter, résiste bien au froid léger.",winter:"Peut tenir sous voile, sinon ressème au printemps."}},
  { key:'ciboulette', name:'Ciboulette', emoji:'🪴', category:'Aromates', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Ciboulette',
    desc:"Vivace très facile, repousse vite après la coupe.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre dès les beaux jours, divise si touffe âgée.",summer:"Coupe ras régulièrement pour une repousse tendre.",autumn:"Dernière coupe avant le repos hivernal.",winter:"Feuillage disparaît, la souche reste en vie."}},
  { key:'thym', name:'Thym', emoji:'🌾', category:'Aromates', freq:4, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Thym',
    desc:"Méditerranéen, déteste l'excès d'eau. Sol drainant indispensable.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'taille',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille légère pour densifier la touffe.",summer:"Laisse sécher entre arrosages, résiste très bien à la canicule.",autumn:"Dernière récolte avant que la pousse ne ralentisse.",winter:"Très rustique, ne craint pas le froid sec."}},
  { key:'thym_citron', name:'Thym citronné', emoji:'🍋', category:'Aromates', freq:4, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Thymus_citriodorus',
    desc:"Variété parfumée au citron, mêmes besoins que le thym commun.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'taille',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille après floraison pour garder une forme compacte.",summer:"Très résistant à la sécheresse, n'arrose presque pas.",autumn:"Ralentit naturellement, réduis l'arrosage.",winter:"Protège si pot exposé au gel intense."}},
  { key:'romarin', name:'Romarin', emoji:'🌲', category:'Aromates', freq:5, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Romarin',
    desc:"Arbrisseau méditerranéen très résistant à la sécheresse.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'floraison',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Belle floraison bleue, les abeilles adorent.",summer:"Quasi aucun arrosage nécessaire, sol sec toléré.",autumn:"Taille légère pour garder la forme.",winter:"Rustique jusqu'à -10°C selon variété."}},
  { key:'basilic_thai', name:'Basilic thaï', emoji:'🌿', category:'Aromates', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Basilic_thaï',
    desc:"Variété asiatique anisée, mêmes besoins que le basilic classique.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante au chaud après tout risque de gel.",summer:"Pince régulièrement pour éviter la floraison précoce.",autumn:"Rentre à l'intérieur si tu veux prolonger.",winter:"Ne supporte pas le froid, annuelle."}},
  { key:'coriandre', name:'Coriandre', emoji:'🌱', category:'Aromates', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Coriandre',
    desc:"Monte en graine rapidement par forte chaleur, ressemer souvent.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'recolte',6:'recolte',7:'dormant',8:'plantation',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème par petites quantités échelonnées.",summer:"Monte vite en graine si trop chaud, ressème toutes les 3 semaines.",autumn:"Reprend bien avec la fraîcheur, ressème.",winter:"Repos, ressème au printemps."}},
  { key:'sauge', name:'Sauge', emoji:'🌿', category:'Aromates', freq:4, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Sauge_officinale',
    desc:"Vivace robuste, tolère bien la sécheresse une fois installée.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'taille',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille les tiges ligneuses pour stimuler les jeunes pousses.",summer:"Arrosage minimal, déteste l'humidité stagnante.",autumn:"Taille légère avant l'hiver.",winter:"Rustique, protège juste les jeunes plants."}},
  { key:'origan', name:'Origan', emoji:'🌿', category:'Aromates', freq:4, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Origan',
    desc:"Méditerranéen, parfum plus fort en conditions sèches.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Divise les touffes âgées pour les revigorer.",summer:"Récolte avant floraison pour un goût plus intense.",autumn:"Dernière coupe avant le repos.",winter:"Les parties aériennes peuvent jaunir, normal."}},
  { key:'basilic_citron', name:'Basilic citron', emoji:'🍋', category:'Aromates', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Basilic',
    desc:"Variété parfumée au citron, fragile comme le basilic classique.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante au chaud, sensible au froid.",summer:"Arrose tous les jours, jamais sur le feuillage.",autumn:"Rentre en intérieur si possible.",winter:"Ne survit pas au gel."}},
  { key:'estragon', name:'Estragon', emoji:'🌿', category:'Aromates', freq:3, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Estragon',
    desc:"Vivace au goût anisé, apprécie un sol bien drainé.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre tardivement, sois patient.",summer:"Récolte régulière stimule la pousse.",autumn:"Coupe avant les premières gelées.",winter:"Disparaît en surface, repart en mai."}},
  { key:'aneth', name:'Aneth', emoji:'🌿', category:'Aromates', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Aneth',
    desc:"Annuelle qui monte vite en graine, à ressemer régulièrement.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'recolte',6:'recolte',7:'recolte',8:'dormant',9:'plantation',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème directement en pot, n'aime pas être transplanté.",summer:"Monte vite en graine par forte chaleur.",autumn:"Ressème pour une récolte d'automne.",winter:"Annuelle, recommence chaque année."}},
  { key:'laurier', name:'Laurier-sauce', emoji:'🌿', category:'Aromates', freq:5, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Laurier_noble',
    desc:"Arbuste persistant à croissance lente, très résistant.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille pour donner une forme si besoin.",summer:"Tolère bien la sécheresse, arrosage occasionnel.",autumn:"Récolte les feuilles pour faire sécher.",winter:"Protège du gel intense en dessous de -5°C."}},

  // ───────── FLEURS ─────────
  { key:'oeillet', name:'Œillets', emoji:'💐', category:'Fleurs', freq:3, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Dianthus',
    desc:"Vivace florale facile, fleurit longtemps avec peu d'entretien.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'taille',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Retire les fleurs fanées de l'hiver précédent.",summer:"Coupe les fleurs fanées pour prolonger la floraison.",autumn:"Rabats légèrement avant le repos hivernal.",winter:"Rustique, supporte bien le froid."}},
  { key:'kalanchoe', name:'Kalanchoé', emoji:'🌸', category:'Fleurs', freq:7, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Kalanchoe',
    desc:"Plante grasse fleurie, déteste l'excès d'eau et le gel.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'floraison',5:'floraison',6:'floraison',7:'croissance',8:'croissance',9:'croissance',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Reprend sa floraison avec la lumière croissante.",summer:"Arrosage minimal, laisse sécher complètement entre deux.",autumn:"Rentre à l'intérieur avant les premières fraîcheurs.",winter:"Ne supporte pas le gel, garde en intérieur lumineux."}},
  { key:'geranium', name:'Géranium', emoji:'🌺', category:'Fleurs', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Pelargonium',
    desc:"Classique du balcon, floraison abondante tout l'été.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'floraison',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sors après les dernières gelées, taille les tiges abîmées.",summer:"Retire les fleurs fanées chaque semaine pour prolonger.",autumn:"Rentre avant le premier gel si tu veux le garder.",winter:"Hiverne en intérieur frais et lumineux, 8-10°C idéal."}},
  { key:'petunia', name:'Pétunia', emoji:'🌸', category:'Fleurs', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Petunia',
    desc:"Floraison spectaculaire mais gourmande en eau et en engrais.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'floraison',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante après les gelées, pince pour ramifier.",summer:"Arrose tous les jours, engrais hebdomadaire pour la floraison continue.",autumn:"Termine sa floraison, peut être traité en annuelle.",winter:"Meurt au gel, généralement à reesemer."}},
  { key:'lavande', name:'Lavande', emoji:'💜', category:'Fleurs', freq:5, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Lavande',
    desc:"Méditerranéenne emblématique, déteste l'humidité stagnante.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'floraison',7:'floraison',8:'taille',9:'dormant',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille légère pour densifier avant la pousse.",summer:"Arrosage minimal, magnifique floraison parfumée.",autumn:"Taille après floraison pour garder une forme compacte.",winter:"Très rustique, ne craint pas le froid sec."}},
  { key:'surfinia', name:'Surfinia', emoji:'🌸', category:'Fleurs', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Petunia',
    desc:"Pétunia retombant idéal pour suspensions et jardinières.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'floraison',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante en jardinière après les gelées.",summer:"Arrosage quotidien indispensable, engrais régulier.",autumn:"Floraison se termine avec le froid.",winter:"Ne résiste pas au gel."}},
  { key:'marguerite', name:'Marguerite', emoji:'🌼', category:'Fleurs', freq:3, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Marguerite_(fleur)',
    desc:"Vivace florale facile, floraison longue et généreuse.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'taille',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre vite, divise si touffe trop dense.",summer:"Retire les fleurs fanées pour stimuler de nouvelles.",autumn:"Rabats après floraison.",winter:"Résiste au froid léger en pot protégé."}},
  { key:'bégonia', name:'Bégonia', emoji:'🌺', category:'Fleurs', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Begonia',
    desc:"Apprécie la mi-ombre, idéal pour balcon peu ensoleillé.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'floraison',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante après les gelées, préfère la mi-ombre.",summer:"Garde le substrat frais sans excès d'eau.",autumn:"Rentre les tubercules si tu veux les garder.",winter:"Ne supporte pas le gel."}},
  { key:'verveine', name:'Verveine citronnelle', emoji:'🌿', category:'Aromates', freq:3, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Verveine_citronnelle',
    desc:"Arbuste parfumé au citron, utilisé en tisane.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Reprise tardive, sois patient jusqu'en avril-mai.",summer:"Récolte les feuilles pour tisane, parfum plus fort le matin.",autumn:"Taille avant l'hiver, rentre si pot exposé.",winter:"Craint le gel, protège ou rentre en intérieur."}},

  // ───────── PLANTES EXOTIQUES / MOINS COURANTES ─────────
  { key:'citronnier', name:'Citronnier', emoji:'🍋', category:'Fruits exotiques', freq:3, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Citronnier',
    desc:"Agrume en pot, craint le gel, demande beaucoup de lumière.",
    months:{1:'dormant',2:'dormant',3:'floraison',4:'floraison',5:'croissance',6:'croissance',7:'croissance',8:'croissance',9:'recolte',10:'recolte',11:'recolte',12:'dormant'},
    seasonTips:{spring:"Floraison parfumée, sors le pot progressivement.",summer:"Arrosage régulier, engrais agrumes toutes les 2 semaines.",autumn:"Récolte les fruits mûrs, rentre avant le premier froid.",winter:"Hiverne en intérieur lumineux et frais (5-10°C)."}},
  { key:'olivier', name:'Olivier', emoji:'🫒', category:'Fruits exotiques', freq:6, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Olivier',
    desc:"Méditerranéen très résistant à la sécheresse une fois établi.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'floraison',5:'floraison',6:'croissance',7:'croissance',8:'croissance',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Taille légère, floraison discrète mais essentielle.",summer:"Arrosage minimal, résiste très bien à la canicule.",autumn:"Récolte les olives si mûres.",winter:"Rustique jusqu'à -7°C, protège si pot petit."}},
  { key:'figuier', name:'Figuier', emoji:'🌳', category:'Fruits exotiques', freq:3, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Figuier_commun',
    desc:"Bel arbuste fruitier, perd ses feuilles en hiver.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'croissance',5:'croissance',6:'croissance',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Débourre tardivement, patience.",summer:"Arrosage régulier pendant la fructification.",autumn:"Dernière récolte, les feuilles jaunissent et tombent.",winter:"Perd ses feuilles, protège les racines du gel intense."}},
  { key:'menthe_poivree', name:'Menthe poivrée', emoji:'🌿', category:'Aromates', freq:1, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Menthe_poivrée',
    desc:"Hybride très parfumé, même comportement envahissant que la menthe.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre vite, isole bien le pot.",summer:"Garde humide en permanence.",autumn:"Coupe avant l'hiver.",winter:"Repart au printemps suivant."}},
  { key:'capucine', name:'Capucine', emoji:'🌻', category:'Fleurs', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Capucine',
    desc:"Fleurs et feuilles comestibles, repousse les pucerons.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'floraison',7:'floraison',8:'floraison',9:'floraison',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème directement après les gelées.",summer:"Floraison continue, peu d'entretien nécessaire.",autumn:"Termine avec les premières fraîcheurs.",winter:"Annuelle, meurt au gel."}},
  { key:'soucis', name:'Soucis (Calendula)', emoji:'🌼', category:'Fleurs', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Calendula_officinalis',
    desc:"Fleur comestible et médicinale, très facile à cultiver.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'floraison',6:'floraison',7:'floraison',8:'floraison',9:'floraison',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème tôt, germe facilement.",summer:"Retire les fleurs fanées pour prolonger.",autumn:"Peut refleurir si températures douces.",winter:"Annuelle, se ressème parfois spontanément."}},
  { key:'ail', name:'Ail', emoji:'🧄', category:'Légumes', freq:5, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Ail',
    desc:"Bulbe facile, se plante en automne pour récolte en été.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'dormant',9:'dormant',10:'plantation',11:'plantation',12:'dormant'},
    seasonTips:{spring:"Croissance active, arrosage modéré.",summer:"Récolte quand les feuilles jaunissent, fais sécher.",autumn:"Plante les gousses pour l'année suivante.",winter:"Repos sous terre, résiste au froid."}},
  { key:'oignon', name:'Oignon', emoji:'🧅', category:'Légumes', freq:3, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Oignon',
    desc:"Facile en pot profond, demande peu d'entretien.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'croissance',6:'croissance',7:'recolte',8:'recolte',9:'dormant',10:'plantation',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante les bulbilles dans un pot profond.",summer:"Récolte quand le feuillage se couche.",autumn:"Possibilité de planter des oignons d'hiver.",winter:"Variétés d'hiver résistent au froid."}},
  { key:'radis', name:'Radis', emoji:'🥕', category:'Légumes', freq:1, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Radis',
    desc:"Croissance ultra rapide, idéal pour débuter en pot.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'recolte',5:'recolte',6:'dormant',7:'dormant',8:'plantation',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème directement, récolte en 3-4 semaines.",summer:"Évite de semer en pleine chaleur, monte en graine.",autumn:"Bonne période pour ressemer.",winter:"Pas de culture en pleine saison froide."}},
  { key:'salade', name:'Salade', emoji:'🥬', category:'Légumes', freq:1, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Laitue',
    desc:"Facile et rapide, préfère la fraîcheur à la chaleur intense.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'recolte',6:'recolte',7:'dormant',8:'plantation',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante échelonné toutes les 2 semaines.",summer:"Monte en graine vite par forte chaleur, privilégie la mi-ombre.",autumn:"Excellente période, repique régulièrement.",winter:"Variétés résistantes au froid possibles sous voile."}},
  { key:'epinard', name:'Épinard', emoji:'🥬', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Épinard',
    desc:"Préfère la fraîcheur, monte vite en graine en été.",
    months:{1:'dormant',2:'plantation',3:'croissance',4:'recolte',5:'recolte',6:'dormant',7:'dormant',8:'dormant',9:'plantation',10:'recolte',11:'recolte',12:'dormant'},
    seasonTips:{spring:"Sème tôt avant les chaleurs.",summer:"Évite la culture en plein été, monte en graine.",autumn:"Excellente saison pour semer.",winter:"Résiste bien au froid léger."}},
  { key:'fraise_des_bois', name:'Fraise des bois', emoji:'🍓', category:'Fruits', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Fragaria_vesca',
    desc:"Petite vivace au goût intense, idéale en bordure de pot.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre facilement, peu d'entretien.",summer:"Récolte continue jusqu'à l'automne.",autumn:"Dernières récoltes avant le repos.",winter:"Très rustique, tolère le froid."}},
  { key:'myrtillier', name:'Myrtillier', emoji:'🫐', category:'Fruits', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Myrtille',
    desc:"Demande un sol acide (terre de bruyère), arrosage à l'eau non calcaire.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'floraison',5:'floraison',6:'croissance',7:'recolte',8:'recolte',9:'taille',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Floraison délicate, protège des gelées tardives.",summer:"Récolte échelonnée, arrose à l'eau de pluie de préférence.",autumn:"Taille légère après récolte.",winter:"Rustique, perd ses feuilles selon variété."}},
  { key:'groseillier', name:'Groseillier', emoji:'🍒', category:'Fruits', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Groseillier',
    desc:"Arbuste fruitier rustique, fructifie dès la 2e année.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'floraison',5:'croissance',6:'recolte',7:'recolte',8:'taille',9:'dormant',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Floraison discrète, protège des gelées.",summer:"Récolte par grappes, arrosage régulier.",autumn:"Taille après récolte pour aérer.",winter:"Très rustique, ne craint pas le froid."}},
  { key:'physalis', name:'Physalis', emoji:'🍊', category:'Fruits exotiques', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Physalis_peruviana',
    desc:"Fruit exotique facile en climat tempéré, lanternes décoratives.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'croissance',7:'floraison',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante après les gelées, croissance vigoureuse.",summer:"Arrosage modéré, tuteure si nécessaire.",autumn:"Récolte quand l'enveloppe brunit.",winter:"Annuelle en climat tempéré."}},
  { key:'sarriette', name:'Sarriette', emoji:'🌿', category:'Aromates', freq:4, waterNeed:'low',
    wiki:'https://fr.wikipedia.org/wiki/Sarriette',
    desc:"Aromate méditerranéen peu exigeant, parfait en sol pauvre.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre facilement, taille légère.",summer:"Très résistant à la sécheresse.",autumn:"Dernière récolte avant le repos.",winter:"Rustique en climat tempéré."}},
  { key:'marjolaine', name:'Marjolaine', emoji:'🌿', category:'Aromates', freq:3, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Marjolaine',
    desc:"Proche de l'origan, parfum plus délicat et sucré.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'dormant',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante après les dernières gelées.",summer:"Récolte avant floraison pour un goût optimal.",autumn:"Termine la récolte, traité souvent en annuelle.",winter:"Peu rustique, à protéger ou ressemer."}},
  { key:'ciboule', name:'Ciboule (oignon vert)', emoji:'🧅', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Ciboule',
    desc:"Proche de l'oignon, se récolte en vert toute l'année.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'recolte',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Reprend vite, divise si touffe dense.",summer:"Récolte au fur et à mesure des besoins.",autumn:"Continue la récolte tant que le froid n'arrive pas.",winter:"Résiste assez bien sous voile."}},
  { key:'roquette', name:'Roquette', emoji:'🥬', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Roquette_(plante)',
    desc:"Pousse vite, goût plus piquant en conditions sèches.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'recolte',5:'recolte',6:'dormant',7:'dormant',8:'plantation',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème directement, récolte en 4 semaines.",summer:"Monte vite en graine, privilégie l'ombre légère.",autumn:"Excellente saison pour semer à nouveau.",winter:"Sous voile, peut résister au froid léger."}},
  { key:'cresson', name:'Cresson', emoji:'🥬', category:'Légumes', freq:1, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Cresson',
    desc:"Besoin d'un substrat constamment humide, presque aquatique.",
    months:{1:'dormant',2:'plantation',3:'croissance',4:'recolte',5:'recolte',6:'recolte',7:'dormant',8:'plantation',9:'recolte',10:'recolte',11:'recolte',12:'dormant'},
    seasonTips:{spring:"Sème dans un substrat gardé détrempé.",summer:"Arrose 2x/jour, ne doit jamais sécher.",autumn:"Bonne saison, fraîcheur idéale.",winter:"Peut continuer en intérieur lumineux."}},
  { key:'chou_kale', name:'Chou kale', emoji:'🥬', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Chou_kale',
    desc:"Très résistant au froid, peut se récolter tout l'hiver.",
    months:{1:'recolte',2:'recolte',3:'dormant',4:'plantation',5:'croissance',6:'croissance',7:'croissance',8:'croissance',9:'recolte',10:'recolte',11:'recolte',12:'recolte'},
    seasonTips:{spring:"Plante en pot profond, croissance lente au début.",summer:"Arrosage régulier, surveille les chenilles.",autumn:"Le goût s'améliore avec le froid.",winter:"Récolte possible même sous la neige légère."}},
  { key:'pois_gourmand', name:'Pois gourmand', emoji:'🫛', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Pois',
    desc:"Grimpant, nécessite un tuteur ou treillis en pot.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'floraison',6:'recolte',7:'recolte',8:'dormant',9:'plantation',10:'croissance',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème tôt, installe un tuteur dès la plantation.",summer:"Récolte régulière stimule la production.",autumn:"Deuxième culture possible en climat doux.",winter:"Ne résiste pas au gel prolongé."}},
  { key:'betterave', name:'Betterave', emoji:'🟣', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Betterave_potagère',
    desc:"Racine facile en pot profond, feuilles aussi comestibles.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'plantation',9:'croissance',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème dans un pot profond (min 25cm).",summer:"Récolte quand la racine atteint 5-7cm.",autumn:"Deuxième semis possible en climat doux.",winter:"Récolte avant les fortes gelées."}},
  { key:'carotte', name:'Carotte', emoji:'🥕', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Carotte',
    desc:"Nécessite un pot très profond pour une racine droite.",
    months:{1:'dormant',2:'dormant',3:'plantation',4:'croissance',5:'croissance',6:'croissance',7:'recolte',8:'recolte',9:'plantation',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Sème dans un pot d'au moins 30cm de profondeur.",summer:"Arrosage régulier pour éviter les racines fourchues.",autumn:"Récolte avant les fortes gelées.",winter:"Variétés d'hiver possibles sous voile."}},
  { key:'menthe_marocaine', name:'Menthe marocaine', emoji:'🌿', category:'Aromates', freq:1, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Menthe',
    desc:"Variété douce idéale pour le thé, même comportement que la menthe classique.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'croissance',6:'recolte',7:'recolte',8:'recolte',9:'recolte',10:'taille',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Redémarre vigoureusement, isole le pot.",summer:"Garde humide en permanence.",autumn:"Coupe avant l'hiver.",winter:"Repart au printemps suivant."}},
  { key:'fenouil', name:'Fenouil', emoji:'🌿', category:'Légumes', freq:2, waterNeed:'medium',
    wiki:'https://fr.wikipedia.org/wiki/Fenouil',
    desc:"Aromatique et légume à la fois, le bulbe demande un grand pot.",
    months:{1:'dormant',2:'dormant',3:'dormant',4:'plantation',5:'croissance',6:'croissance',7:'croissance',8:'recolte',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Plante après les gelées, sol riche nécessaire.",summer:"Arrosage régulier pour un bulbe tendre.",autumn:"Récolte avant les premières gelées.",winter:"Ne résiste pas bien au gel."}},
  { key:'bananier', name:'Bananier', emoji:'🍌', category:'Fruits exotiques', freq:2, waterNeed:'high',
    wiki:'https://fr.wikipedia.org/wiki/Bananier',
    desc:"Plante tropicale à très grand développement, exige beaucoup d'eau, de chaleur et un pot profond. Craint le gel et le vent fort.",
    months:{1:'dormant',2:'dormant',3:'croissance',4:'croissance',5:'croissance',6:'croissance',7:'floraison',8:'floraison',9:'recolte',10:'recolte',11:'dormant',12:'dormant'},
    seasonTips:{spring:"Reprise de croissance rapide dès que les températures dépassent 15°C, sors-le progressivement.",summer:"Arrosage très généreux et fréquent, le bananier est très gourmand en eau, apporte de l'engrais riche en potassium toutes les 2 semaines.",autumn:"Ralentit avec la fraîcheur, rentre-le avant les premières nuits sous 12°C.",winter:"Hiverne impérativement en intérieur lumineux (min 12-15°C), réduis fortement l'arrosage, ne craint rien tant qu'il est protégé du gel."}},
];

// Helper: obtenir la liste des catégories
function getCategories(){
  return [...new Set(PLANT_LIBRARY.map(p=>p.category))].sort();
}

// Helper: phase actuelle d'une plante de la bibliothèque
function getCurrentPhase(libPlant){
  const month=new Date().getMonth()+1;
  return libPlant.months[month]||'dormant';
}

// Helper: prochaine transition de phase
function getNextPhaseChange(libPlant){
  const month=new Date().getMonth()+1;
  const current=libPlant.months[month];
  for(let i=1;i<=12;i++){
    const m=((month-1+i)%12)+1;
    if(libPlant.months[m]!==current){
      return {month:m,phase:libPlant.months[m]};
    }
  }
  return null;
}
